name: Bug Report
about: Report a bug or issue
title: "[BUG] "
labels: ["type: bug", "status: needs-triage"]
assignees: ""

---

## 🐛 Bug Description

A clear and concise description of what the bug is.

## 📋 Steps to Reproduce

1. Go to '...'
2. Click on '...'
3. Hover over '...'
4. See error

## ✅ Expected Behavior

What you expected to happen.

## ❌ Actual Behavior

What actually happened.

## 🖼️ Screenshots

If applicable, add screenshots to help explain the problem.

## 🔧 Environment

**Required:**
- Obsidian Version: [e.g. 1.5.3]
- Plugin Version: [e.g. 1.0.0]
- Operating System: [e.g. macOS 14.1, Windows 11, Linux Ubuntu 22.04]

**Optional:**
- Installation Method: [Community Plugins / Manual]
- Other installed plugins that might conflict:

## 📝 Console Logs

Open Developer Console (Cmd/Ctrl + Shift + I) and paste any errors:

```
Paste console errors here
```

## 🔍 Additional Context

- Does this happen in a specific vault or all vaults?
- Does it happen with specific note content?
- Any other relevant information

## 🔄 Reproduction Rate

How often does this bug occur?

- [ ] Always (100%)
- [ ] Frequently (>50%)
- [ ] Sometimes (>25%)
- [ ] Rarely (<25%)

## ✔️ Checklist

- [ ] I have checked existing issues to avoid duplicates
- [ ] I have tested with the latest version of the plugin
- [ ] I have checked the console for error messages
- [ ] I have tried disabling other plugins to isolate the issue
- [ ] I have included all required environment information
